// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
import java.util.*;
class Main {
   public static void main(String args[]) throws Exception {
    MyTree t = new MyTree();
    t.load();
    int choice;
    Scanner sca = new Scanner(System.in);
    System.out.println();
    System.out.println(" 1. Test f1 - show all nodes in the tree");
    System.out.println(" 2. Test f2 - search node");
    System.out.println(" 3. Test f3 - count nodes");
    System.out.println(" 4. Test . . . ");
    System.out.print("    Your selection (1 -> n): ");
    choice = sca.nextInt();
    sca.nextLine();
    switch(choice) {
       case 1: 
           System.out.println("Tree:");
           t.preOrder();
           break;
       case 2: 
           System.out.println("Tree:");
           t.preOrder();
           boolean r = t.search(10);
           System.out.println("\nSearch result:" + r);
           
           break;
       case 3: 
           System.out.println("Tree:");
           t.preOrder();
           int rs = t.countNode();
           System.out.println("\nNodes in the tree: " + rs + "  nodes");
           break;
       default: System.out.println("Wrong selection");
      }
     System.out.println();
   }      
 }
